version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install for static HTML"
  build:
    commands:
      - echo "Preparing deployment..."
  post_build:
    commands:
      - echo "Syncing files to S3..."
      - aws s3 sync . s3://my-frontend-s3-app --delete

artifacts:
  files:
    - '**/*'
  discard-paths: yes
